vim.opt.termguicolors = true -- Enable 24-bit colors
vim.opt.number = true -- Show line numbers
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.signcolumn = "yes" -- Always show sign column
vim.opt.cursorline = true -- Highlight current line
vim.opt.winborder = "rounded" -- Rounded popup borders
vim.opt.scrolloff = 12 -- Context lines above/below cursor
vim.opt.mouse = "a" -- Enable mouse support
vim.opt.mousescroll = "ver:3,hor:0" -- Smooth vertical scroll (3 lines per tick), disable horizontal
vim.opt.showmode = false -- Hide mode indicator
vim.opt.splitright = true -- Vertical splits go right
vim.opt.splitbelow = true -- Horizontal splits go below
vim.opt.timeoutlen = 300 -- Keymap timeout
vim.opt.updatetime = 250 -- Faster diagnostics
vim.opt.ignorecase = true -- Case-insensitive search...
vim.opt.smartcase = true -- ...unless uppercase in pattern
vim.opt.inccommand = "split" -- Live substitution preview
vim.opt.clipboard = "unnamedplus" -- System clipboard
vim.opt.breakindent = true -- Preserve indent on wrapped lines
vim.opt.undofile = true -- Persistent undo
vim.opt.swapfile = false -- Disable swap files
vim.g.autoformat = true -- Custom: enable auto-formatting
vim.opt.tabstop = 2 -- Tab width (display)
vim.opt.shiftwidth = 2 -- Indent width
vim.opt.expandtab = true -- Convert tabs to spaces
vim.opt.textwidth = 120 -- Auto-wrap at 80 columns
vim.opt.foldenable = false -- Start with all folds open
vim.opt.wrap = true -- Disable line wrapping
vim.opt.foldlevel = 99 -- Keep folds open by default
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
