Pack({ "nvim-mini/mini.nvim" })

require("mini.basics").setup()
require("mini.icons").setup()
require("mini.statusline").setup()
require("mini.ai").setup()
require("mini.move").setup()
require("mini.clue").setup()
require("mini.diff").setup()
require("mini.indentscope").setup()
require("mini.completion").setup()
require("mini.notify").setup()
require("mini.pairs").setup()
require("mini.snippets").setup()
require("mini.surround").setup()
