gui:
  nerdFontsVersion: "3"
  showIcons: true
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  mouseEvents: true
  scrollHeight: 5
  theme:
    activeBorderColor:
      - "#d8a657"   # gruvbox yellow
      - bold
    inactiveBorderColor:
      - "#928374"   # gruvbox gray
    optionsTextColor:
      - "#7daea3"   # gruvbox aqua
    selectedLineBgColor:
      - "#3c3836"   # gruvbox bg1
    selectedRangeBgColor:
      - "#3c3836"
    cherryPickedCommitBgColor:
      - "#45403d"
    cherryPickedCommitFgColor:
      - "#d8a657"
    unstagedChangesColor:
      - "#e46876"   # gruvbox red
    defaultFgColor:
      - "#dfbf8e"   # gruvbox fg

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --side-by-side
  autoFetch: true
  autoRefresh: true
  fetchInterval: 60
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium"
  commit:
    signOff: false

refresher:
  refreshInterval: 10
  fetchInterval: 60

keybinding:
  universal:
    quit: "q"
    prevItem: "k"
    nextItem: "j"
    prevBlock: "h"
    nextBlock: "l"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdn>"
